language: node_js
addons:
  chrome: stable
node_js:
  - 12
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @lhci/cli@0.6.x
script:
  - yarn test:unit
before_deploy:
  - npm install netlify-cli -g
  - yarn build
  - lhci autorun
  
deploy:
  provider: script
  edge: true
  script: netlify deploy --dir=dist --prod
  on:
    branch: main